<td <?php if(($month == 01) && ($activitymonthdetailsover <= $actcount) && ( $actcount != 0)) { ?> style="background-color: green;" <?php }else{ ?> style="background-color: red;" <?php } ?> ><?php if(($month == 01)&& ( $actcount != 0) ) {  ?> <?php echo $actcount; ?> <?php }else{ ?> 0 <?php } ?></td>
<td <?php if(($month == 02) && ($activitymonthdetailsover <= $actcount) && ( $actcount != 0 )) {?> style="background-color: green;" <?php }else{ ?> style="background-color: red;" <?php } ?> ><?php if(($month == 02)&& ( $actcount != 0) ) {?> <?php echo $actcount; ?> <?php }else{ ?> 0 <?php } ?></td>
<td <?php if(($month == 03) && ($activitymonthdetailsover <= $actcount) && ( $actcount != 0 )) {?> style="background-color: green;" <?php }else{ ?> style="background-color: red;" <?php } ?> ><?php if(($month == 03) && ( $actcount != 0)) {?> <?php echo $actcount; ?> <?php }else{ ?> 0 <?php } ?></td>
<td <?php if(($month == 04) && ($activitymonthdetailsover <= $actcount) && ( $actcount != 0 )) {?> style="background-color: green;" <?php }else{ ?> style="background-color: red;" <?php } ?> ><?php if(($month == 04) && ( $actcount != 0)) {?> <?php echo $actcount; ?> <?php }else{ ?> 0 <?php } ?></td>
<td <?php if(($month == 05) && ($activitymonthdetailsover <= $actcount) && ( $actcount != 0 )) {?> style="background-color: green;" <?php }else{ ?> style="background-color: red;" <?php } ?> ><?php if(($month == 05) && ( $actcount != 0)) {?> <?php echo $actcount; ?> <?php }else{ ?> 0 <?php } ?></td>
<td <?php if(($month == 06) && ($activitymonthdetailsover <= $actcount) && ( $actcount != 0 )) {?> style="background-color: green;" <?php }else{ ?> style="background-color: red;" <?php } ?> ><?php if(($month == 06)&& ( $actcount != 0) ) {?> <?php echo $actcount; ?> <?php }else{ ?> 0 <?php } ?></td>
<td <?php if(($month == 07) && ($activitymonthdetailsover <= $actcount) && ( $actcount != 0 )) {?> style="background-color: green;" <?php }else{ ?> style="background-color: red;" <?php } ?> ><?php if(($month == 07) && ( $actcount != 0)) {?> <?php echo $actcount; ?> <?php }else{ ?> 0 <?php } ?></td>
<td <?php if(($month == 08) && ($activitymonthdetailsover <= $actcount) && ( $actcount != 0 )) {?> style="background-color: green;" <?php }else{ ?> style="background-color: red;" <?php } ?> ><?php if(($month == 08) && ( $actcount != 0)) {?> <?php echo $actcount; ?> <?php }else{ ?> 0 <?php } ?></td>
<td <?php if(($month == 09) && ($activitymonthdetailsover <= $actcount) && ( $actcount != 0 )) {?> style="background-color: green;" <?php }else{ ?> style="background-color: red;" <?php } ?> ><?php if(($month == 09) && ( $actcount != 0)) {?> <?php echo $actcount; ?> <?php }else{ ?> 0 <?php } ?></td>
<td <?php if(($month == 10) && ($activitymonthdetailsover <= $actcount) && ( $actcount != 0 )) {?> style="background-color: green;" <?php }else{ ?> style="background-color: red;" <?php } ?> ><?php if(($month == 10)&& ( $actcount != 0) ) {?> <?php echo $actcount; ?> <?php }else{ ?> 0 <?php } ?></td>
<td <?php if(($month == 11) && ($activitymonthdetailsover <= $actcount) && ( $actcount != 0 )) {?> style="background-color: green;" <?php }else{ ?> style="background-color: red;" <?php } ?> ><?php if(($month == 11)&& ( $actcount != 0) ) {?> <?php echo $actcount; ?> <?php }else{ ?> 0 <?php } ?></td>
<td <?php if(($month == 12) && ($activitymonthdetailsover <= $actcount) && ( $actcount != 0 )) {?> style="background-color: green;" <?php }else{ ?> style="background-color: red;" <?php } ?> ><?php if(($month == 12)&& ( $actcount != 0) ) {?> <?php echo $actcount; ?> <?php }else{ ?> 0 <?php } ?></td>

</tr>                        
                